# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.x'
    inputs:
      packageType: sdk
      version: 3.1.x

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar Cloud Connection'
      organization: 'sandeep-org'
      scannerMode: 'MSBuild'
      projectKey: 'sonar.gitdemo'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet restore $(buildConfiguration)'

  - task: SonarCloudAnalyze@1
    displayName: 'Run Code Analysis'
